<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
  </PropertyGroup>

  <PropertyGroup>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia.Desktop" Version="11.2.6" />
    <PackageReference Condition="'$(Configuration)' == 'Debug'" Include="Avalonia.Diagnostics" Version="11.2.6" />
    <PackageReference Include="LiveScope.Avalonia.Windows" Version="0.5.335-beta" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\LiveScope.Avalonia.Examples\LiveScope.Avalonia.Examples.csproj"/>
  </ItemGroup>
</Project>
