<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>preview</LangVersion>
  </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="LiveScope.Common" Version="0.5.335-beta" />
    </ItemGroup>

</Project>
